### ISSUE TITLE
BringBackOldIcons not bringing back old icons.

### ISSUE THREAD

**Issue by TheDarkBomber** [CompletelyUnbelievable/BDAddons#2]
Even with this theme enabled, avatars and other icons are still foreignObjects contained within SVGs.

**Comment by CompletelyUnbelievable** [comment]
Sorry it has been a long time, but I've been busy. Chances are that you were using a different theme that messed with it, with how it works that would not be surprising. What is surprising is that it is still working.

Minor issues that I can think of are:
- The help icon seems slightly too small.
- The pin indicator on the pin icon does not have a border.
- The pin icon seen in the chat area is misaligned.
- Might have other chat area related icon issues

My next commit will have the fixes to the minor issues I know about as seen in this image (Line 9 is commented out so that they are aligned in the image):
![image](https://user-images.githubusercontent.com/39345185/71977941-590d6080-31d7-11ea-98b4-e27f3a08b30f.png)
